/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foodtrack;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author monyv
 */
public class AgregarAlimento extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAlimento
     */
    public AgregarAlimento() {
        initComponents();
        SwingUtilities.invokeLater(() -> {
            checarApariencia();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        caloriasInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        porcionInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        unidadInput = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tipoInput = new javax.swing.JComboBox<>();
        cancelarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 244, 192));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 140, 13));
        jLabel1.setText("Agregar Alimento");

        jLabel2.setText("Ingrese los siguientes datos de su alimento:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Calorías:");

        jLabel5.setText("Porción:");

        jLabel6.setText("Unidad:");

        unidadInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "ml", "unidad" }));

        jLabel7.setText("Tipo Alimento:");

        tipoInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "proteinas", "verduras", "carbohidratos", "grasas saludables" }));

        cancelarBtn.setBackground(new java.awt.Color(253, 140, 13));
        cancelarBtn.setText("Cancelar ✘");
        cancelarBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        agregarBtn.setBackground(new java.awt.Color(253, 140, 13));
        agregarBtn.setText("Agregar ✔");
        agregarBtn.setPreferredSize(new java.awt.Dimension(100, 50));
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(porcionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel6)
                                        .addGap(5, 5, 5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unidadInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(caloriasInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(nombreInput, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tipoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(caloriasInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(porcionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(unidadInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        
        
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        // TODO add your handling code here:
        String nombre = nombreInput.getText();
        int calorias = Integer.parseInt(caloriasInput.getText());
        int porcion = Integer.parseInt(porcionInput.getText());
        String unidad = String.valueOf(unidadInput.getSelectedItem());
        String tipo = String.valueOf(tipoInput.getSelectedItem());
        
        boolean agregar = PeticionesDB.agregarAlimento(nombre, calorias, porcion, unidad, tipo);
        if (agregar) {
            JOptionPane.showMessageDialog(this, "Alimento registrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registar el alimento","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void checarApariencia() {
        if (ModoOscuro.getInstance().isModoOscuroActivo()) {
            jPanel1.setBackground(ModoOscuro.getInstance().getFondoOscuro());
            
            //Labels
            jLabel1.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            jLabel2.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            jLabel3.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            jLabel4.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            jLabel5.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            jLabel6.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            jLabel7.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            
            //Botones
            agregarBtn.setBackground(ModoOscuro.getInstance().getBotonesClaro());
            agregarBtn.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            cancelarBtn.setBackground(ModoOscuro.getInstance().getBotonesClaro());
            cancelarBtn.setForeground(ModoOscuro.getInstance().getFuenteClaro());
        } else {
            jPanel1.setBackground(ModoOscuro.getInstance().getFondoClaro());
            
            //Labels
            jLabel1.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            jLabel2.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            jLabel3.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            jLabel4.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            jLabel5.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            jLabel6.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            jLabel7.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            
            //Botones
            agregarBtn.setBackground(ModoOscuro.getInstance().getColorFuerteClaro());
            agregarBtn.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            cancelarBtn.setBackground(ModoOscuro.getInstance().getColorFuerteClaro());
            cancelarBtn.setForeground(ModoOscuro.getInstance().getFuenteClaro());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTextField caloriasInput;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreInput;
    private javax.swing.JTextField porcionInput;
    private javax.swing.JComboBox<String> tipoInput;
    private javax.swing.JComboBox<String> unidadInput;
    // End of variables declaration//GEN-END:variables
}
