/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foodtrack;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author monyv
 */
public class EliminarCuenta extends javax.swing.JFrame {

    /**
     * Creates new form EliminarCuenta
     */
    public EliminarCuenta() {
        initComponents();
        SwingUtilities.invokeLater(() -> {
            checarApariencia();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        eliminarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 244, 192));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Eliminar cuenta");

        jLabel2.setText("Ingrese su contraseña");

        eliminarBtn.setBackground(new java.awt.Color(253, 140, 13));
        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setBackground(new java.awt.Color(253, 140, 13));
        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(eliminarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelarBtn))
                            .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarBtn)
                    .addComponent(cancelarBtn))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        // TODO add your handling code here:
        int idUsuario = UsuarioId.getInstance().getValor();
        String contrasenaUsuario = PeticionesDB.obtenerContrasena(idUsuario);
        String passwordActual = new String (passwordInput.getPassword());

        if (contrasenaUsuario.equals(passwordActual)) {
            boolean eliminar = PeticionesDB.eliminarCuenta(idUsuario);
            if (eliminar) {
                JOptionPane.showMessageDialog(null, "Cuenta eliminada exitosamente ", "Información", JOptionPane.INFORMATION_MESSAGE);
                Login inicio = new Login();
                inicio.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar cuenta", "Error", JOptionPane.ERROR_MESSAGE);
                Perfil miPerfil = new Perfil();
                miPerfil.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        // TODO add your handling code here:
        Perfil miPerfil = new Perfil();
        miPerfil.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void checarApariencia() {
        if (ModoOscuro.getInstance().isModoOscuroActivo()) {
            //Cambiar panel
            jPanel1.setBackground(ModoOscuro.getInstance().getFondoOscuro());
            
            //Cambiar Labels
            jLabel1.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            jLabel2.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            
            //Cambiar botones
            eliminarBtn.setBackground(ModoOscuro.getInstance().getColorFuerteOscuro());
            eliminarBtn.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
            cancelarBtn.setBackground(ModoOscuro.getInstance().getColorFuerteOscuro());
            cancelarBtn.setForeground(ModoOscuro.getInstance().getFuenteOscuro());
        } else {
            //Cambiar panel
            jPanel1.setBackground(ModoOscuro.getInstance().getFondoClaro());
            
            //Cambiar Labels
            jLabel1.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            jLabel2.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            
            //Cambiar botones
            eliminarBtn.setBackground(ModoOscuro.getInstance().getColorFuerteClaro());
            eliminarBtn.setForeground(ModoOscuro.getInstance().getFuenteClaro());
            cancelarBtn.setBackground(ModoOscuro.getInstance().getColorFuerteClaro());
            cancelarBtn.setForeground(ModoOscuro.getInstance().getFuenteClaro());
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordInput;
    // End of variables declaration//GEN-END:variables
}
