/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foodtrack;

/**
 *
 * @author hilar
 */
public class ListaCompras extends javax.swing.JFrame {

    /**
     * Creates new form ListaCompras
     */
    public ListaCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogojLabel = new javax.swing.JLabel();
        AñadirComidajButton = new javax.swing.JButton();
        MetajButton = new javax.swing.JButton();
        ListaDeComprasjButton = new javax.swing.JButton();
        EstadisticasjButton = new javax.swing.JButton();
        PerfiljButton = new javax.swing.JButton();
        ConfiguracionjButton = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();
        PROTEINASjLabel = new javax.swing.JLabel();
        CARBOHIDRATOSjLabel = new javax.swing.JLabel();
        VERDURASjLabel = new javax.swing.JLabel();
        GRASASjLabel = new javax.swing.JLabel();
        SiguientejButton = new javax.swing.JButton();
        HuevojCheckBox = new javax.swing.JCheckBox();
        AtúnjCheckBox = new javax.swing.JCheckBox();
        SardinajCheckBox = new javax.swing.JCheckBox();
        LentejasjCheckBox = new javax.swing.JCheckBox();
        EspinacasjCheckBox = new javax.swing.JCheckBox();
        GuisantesjCheckBox = new javax.swing.JCheckBox();
        GarbanzosjCheckBox = new javax.swing.JCheckBox();
        PescadojCheckBox = new javax.swing.JCheckBox();
        PechugaPollojCheckBox = new javax.swing.JCheckBox();
        CamaronesjCheckBox = new javax.swing.JCheckBox();
        QuesoPanelajCheckBox = new javax.swing.JCheckBox();
        PavojCheckBox = new javax.swing.JCheckBox();
        CarneResjCheckBox = new javax.swing.JCheckBox();
        PanIntegraljCheckBox = new javax.swing.JCheckBox();
        ArrozCocidojCheckBox = new javax.swing.JCheckBox();
        AvenajCheckBox = new javax.swing.JCheckBox();
        PastajCheckBox = new javax.swing.JCheckBox();
        HarinaTrigojCheckBox = new javax.swing.JCheckBox();
        ManzanajCheckBox = new javax.swing.JCheckBox();
        PapayajCheckBox = new javax.swing.JCheckBox();
        PlátanoMadurojCheckBox = new javax.swing.JCheckBox();
        YucaCocidajCheckBox = new javax.swing.JCheckBox();
        CamotejCheckBox = new javax.swing.JCheckBox();
        TortillaTrigojCheckBox = new javax.swing.JCheckBox();
        GalletaIntegraljCheckBox = new javax.swing.JCheckBox();
        PanAvenajCheckBox = new javax.swing.JCheckBox();
        LechugajCheckBox = new javax.swing.JCheckBox();
        BrócolijCheckBox = new javax.swing.JCheckBox();
        ColiflorjCheckBox = new javax.swing.JCheckBox();
        ApiojCheckBox = new javax.swing.JCheckBox();
        PepinojCheckBox = new javax.swing.JCheckBox();
        ZanahoriajCheckBox = new javax.swing.JCheckBox();
        RemolachajCheckBox = new javax.swing.JCheckBox();
        HabaFrescajCheckBox = new javax.swing.JCheckBox();
        PapasjCheckBox = new javax.swing.JCheckBox();
        AcelgasjCheckBox = new javax.swing.JCheckBox();
        BerengenajCheckBox = new javax.swing.JCheckBox();
        AlcachofajCheckBox = new javax.swing.JCheckBox();
        NopalesjCheckBox = new javax.swing.JCheckBox();
        FrutosSecosjCheckBox = new javax.swing.JCheckBox();
        SemillasjCheckBox = new javax.swing.JCheckBox();
        AceitunasjCheckBox = new javax.swing.JCheckBox();
        EdamamejCheckBox = new javax.swing.JCheckBox();
        TahinijCheckBox = new javax.swing.JCheckBox();
        AceiteCocojCheckBox = new javax.swing.JCheckBox();
        HummusjCheckBox = new javax.swing.JCheckBox();
        TofujCheckBox = new javax.swing.JCheckBox();
        AceiteOlivajCheckBox = new javax.swing.JCheckBox();
        SalmónjCheckBox = new javax.swing.JCheckBox();
        SemillaChíajCheckBox = new javax.swing.JCheckBox();
        LecheEnterajCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 175));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        LogojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/foodtrack/Resources/logo_blanco.png"))); // NOI18N

        AñadirComidajButton.setBackground(new java.awt.Color(255, 255, 204));
        AñadirComidajButton.setText("Añadir comida");
        AñadirComidajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirComidajButtonActionPerformed(evt);
            }
        });

        MetajButton.setBackground(new java.awt.Color(255, 255, 204));
        MetajButton.setText("Meta");

        ListaDeComprasjButton.setBackground(new java.awt.Color(255, 255, 204));
        ListaDeComprasjButton.setText("Lista de compras");

        EstadisticasjButton.setBackground(new java.awt.Color(255, 255, 204));
        EstadisticasjButton.setText("Estadísticas");

        PerfiljButton.setBackground(new java.awt.Color(255, 255, 204));
        PerfiljButton.setText("Perfil");

        ConfiguracionjButton.setBackground(new java.awt.Color(255, 255, 204));
        ConfiguracionjButton.setText("Configuración");

        SalirjButton.setBackground(new java.awt.Color(255, 255, 204));
        SalirjButton.setText("Salir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AñadirComidajButton)
                            .addComponent(MetajButton)
                            .addComponent(ListaDeComprasjButton)
                            .addComponent(EstadisticasjButton)
                            .addComponent(PerfiljButton)
                            .addComponent(ConfiguracionjButton))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogojLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalirjButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LogojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AñadirComidajButton)
                .addGap(18, 18, 18)
                .addComponent(MetajButton)
                .addGap(18, 18, 18)
                .addComponent(ListaDeComprasjButton)
                .addGap(18, 18, 18)
                .addComponent(EstadisticasjButton)
                .addGap(18, 18, 18)
                .addComponent(PerfiljButton)
                .addGap(18, 18, 18)
                .addComponent(ConfiguracionjButton)
                .addGap(18, 18, 18)
                .addComponent(SalirjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PROTEINASjLabel.setForeground(new java.awt.Color(255, 51, 0));
        PROTEINASjLabel.setText("PROTEÍNAS");

        CARBOHIDRATOSjLabel.setForeground(new java.awt.Color(255, 51, 0));
        CARBOHIDRATOSjLabel.setText("CARBOHIDRATOS");

        VERDURASjLabel.setForeground(new java.awt.Color(255, 51, 0));
        VERDURASjLabel.setText("VERDURAS");

        GRASASjLabel.setForeground(new java.awt.Color(255, 51, 0));
        GRASASjLabel.setText("GRASAS SALUDABLES");

        SiguientejButton.setBackground(new java.awt.Color(255, 102, 0));
        SiguientejButton.setText("SIGUIENTE>");
        SiguientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguientejButtonActionPerformed(evt);
            }
        });

        HuevojCheckBox.setText("HUEVO");

        AtúnjCheckBox.setText("LATA DE ATÚN");
        AtúnjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtúnjCheckBoxActionPerformed(evt);
            }
        });

        SardinajCheckBox.setText("SARDINA");

        LentejasjCheckBox.setText("LENTEJAS");

        EspinacasjCheckBox.setText("ESPINACAS");

        GuisantesjCheckBox.setText("GUISANTES");

        GarbanzosjCheckBox.setText("GARBANZOS ");

        PescadojCheckBox.setText("PESCADO");

        PechugaPollojCheckBox.setText("PECHUGA DE POLLO");

        CamaronesjCheckBox.setText("CAMARONES");

        QuesoPanelajCheckBox.setText("QUESO PANELA");

        PavojCheckBox.setText("PAVO");

        CarneResjCheckBox.setText("CARNE DE RES");

        PanIntegraljCheckBox.setText("PAN INTEGRAL");

        ArrozCocidojCheckBox.setText("ARROZ COCIDO");

        AvenajCheckBox.setText("AVENA");

        PastajCheckBox.setText("PASTA");

        HarinaTrigojCheckBox.setText("HARINA DE TRIGO");

        ManzanajCheckBox.setText("MANZANA");

        PapayajCheckBox.setText("PAPAYA");

        PlátanoMadurojCheckBox.setText("PLÁTANO MADURO");

        YucaCocidajCheckBox.setText("YUCA COCIDA");

        CamotejCheckBox.setText("CAMOTE");

        TortillaTrigojCheckBox.setText("TORTILLA DE TRIGO");

        GalletaIntegraljCheckBox.setText("GALLETA INTEGRAL");

        PanAvenajCheckBox.setText("PAN DE AVENA");

        LechugajCheckBox.setText("LECHUGA");

        BrócolijCheckBox.setText("BRÓCOLI");

        ColiflorjCheckBox.setText("COLIFLOR");

        ApiojCheckBox.setText("APIO");

        PepinojCheckBox.setText("PEPINO");

        ZanahoriajCheckBox.setText("ZANAHORIA");

        RemolachajCheckBox.setText("REMOLACHA");

        HabaFrescajCheckBox.setText("HABA FRESCA");

        PapasjCheckBox.setText("PAPAS");

        AcelgasjCheckBox.setText("ACELGAS");

        BerengenajCheckBox.setText("BERENGENA");

        AlcachofajCheckBox.setText("ALCACHOFA");

        NopalesjCheckBox.setText("NOPALES");

        FrutosSecosjCheckBox.setText("FRUTOS SECOS");

        SemillasjCheckBox.setText("SEMILLAS");

        AceitunasjCheckBox.setText("ACEITUNAS");

        EdamamejCheckBox.setText("EDAMAME");

        TahinijCheckBox.setText("TAHINI");

        AceiteCocojCheckBox.setText("ACEITE DE COCO");

        HummusjCheckBox.setText("HUMMUS");

        TofujCheckBox.setText("TOFU");

        AceiteOlivajCheckBox.setText("ACEITE DE OLIVA");

        SalmónjCheckBox.setText("SALMÓN");

        SemillaChíajCheckBox.setText("SEMILLAS DE CHÍA");

        LecheEnterajCheckBox.setText("LECHE ENTERA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CarneResjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QuesoPanelajCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(PavojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PanAvenajCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NopalesjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(SiguientejButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(GalletaIntegraljCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AlcachofajCheckBox))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TortillaTrigojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BerengenajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PROTEINASjLabel)
                            .addComponent(HuevojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AtúnjCheckBox)
                            .addComponent(SardinajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LentejasjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EspinacasjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuisantesjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GarbanzosjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PescadojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PechugaPollojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamaronesjCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CARBOHIDRATOSjLabel)
                                    .addComponent(PanIntegraljCheckBox)
                                    .addComponent(ArrozCocidojCheckBox)
                                    .addComponent(AvenajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PastajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HarinaTrigojCheckBox)
                                    .addComponent(ManzanajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PapayajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PlátanoMadurojCheckBox)
                                    .addComponent(YucaCocidajCheckBox))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VERDURASjLabel)
                                            .addComponent(LechugajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BrócolijCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ColiflorjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ApiojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PepinojCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ZanahoriajCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RemolachajCheckBox)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PapasjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HabaFrescajCheckBox)
                                            .addComponent(AcelgasjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(CamotejCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(GRASASjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FrutosSecosjCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SemillasjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AceitunasjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EdamamejCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TahinijCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AceiteCocojCheckBox)
                                .addComponent(HummusjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TofujCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AceiteOlivajCheckBox)
                                .addComponent(SalmónjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LecheEnterajCheckBox))
                            .addComponent(SemillaChíajCheckBox))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PROTEINASjLabel)
                    .addComponent(CARBOHIDRATOSjLabel)
                    .addComponent(VERDURASjLabel)
                    .addComponent(GRASASjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HuevojCheckBox)
                    .addComponent(PanIntegraljCheckBox)
                    .addComponent(LechugajCheckBox)
                    .addComponent(FrutosSecosjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtúnjCheckBox)
                    .addComponent(ArrozCocidojCheckBox)
                    .addComponent(BrócolijCheckBox)
                    .addComponent(SemillasjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SardinajCheckBox)
                    .addComponent(AvenajCheckBox)
                    .addComponent(ColiflorjCheckBox)
                    .addComponent(AceitunasjCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LentejasjCheckBox)
                    .addComponent(PastajCheckBox)
                    .addComponent(ApiojCheckBox)
                    .addComponent(EdamamejCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspinacasjCheckBox)
                    .addComponent(HarinaTrigojCheckBox)
                    .addComponent(PepinojCheckBox)
                    .addComponent(TahinijCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuisantesjCheckBox)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ManzanajCheckBox)
                        .addComponent(ZanahoriajCheckBox)
                        .addComponent(AceiteCocojCheckBox)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GarbanzosjCheckBox)
                            .addComponent(PapayajCheckBox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HummusjCheckBox)
                            .addComponent(RemolachajCheckBox))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PlátanoMadurojCheckBox)
                        .addComponent(HabaFrescajCheckBox)
                        .addComponent(TofujCheckBox))
                    .addComponent(PescadojCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AceiteOlivajCheckBox)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PechugaPollojCheckBox)
                        .addComponent(YucaCocidajCheckBox))
                    .addComponent(PapasjCheckBox))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CamaronesjCheckBox)
                            .addComponent(CamotejCheckBox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalmónjCheckBox)
                            .addComponent(AcelgasjCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuesoPanelajCheckBox)
                    .addComponent(TortillaTrigojCheckBox)
                    .addComponent(BerengenajCheckBox)
                    .addComponent(SemillaChíajCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PavojCheckBox)
                    .addComponent(AlcachofajCheckBox)
                    .addComponent(LecheEnterajCheckBox)
                    .addComponent(GalletaIntegraljCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiguientejButton)
                    .addComponent(CarneResjCheckBox)
                    .addComponent(PanAvenajCheckBox)
                    .addComponent(NopalesjCheckBox))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirComidajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirComidajButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirComidajButtonActionPerformed

    private void AtúnjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtúnjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtúnjCheckBoxActionPerformed

    private void SiguientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguientejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguientejButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AceiteCocojCheckBox;
    private javax.swing.JCheckBox AceiteOlivajCheckBox;
    private javax.swing.JCheckBox AceitunasjCheckBox;
    private javax.swing.JCheckBox AcelgasjCheckBox;
    private javax.swing.JCheckBox AlcachofajCheckBox;
    private javax.swing.JCheckBox ApiojCheckBox;
    private javax.swing.JCheckBox ArrozCocidojCheckBox;
    private javax.swing.JCheckBox AtúnjCheckBox;
    private javax.swing.JCheckBox AvenajCheckBox;
    private javax.swing.JButton AñadirComidajButton;
    private javax.swing.JCheckBox BerengenajCheckBox;
    private javax.swing.JCheckBox BrócolijCheckBox;
    private javax.swing.JLabel CARBOHIDRATOSjLabel;
    private javax.swing.JCheckBox CamaronesjCheckBox;
    private javax.swing.JCheckBox CamotejCheckBox;
    private javax.swing.JCheckBox CarneResjCheckBox;
    private javax.swing.JCheckBox ColiflorjCheckBox;
    private javax.swing.JButton ConfiguracionjButton;
    private javax.swing.JCheckBox EdamamejCheckBox;
    private javax.swing.JCheckBox EspinacasjCheckBox;
    private javax.swing.JButton EstadisticasjButton;
    private javax.swing.JCheckBox FrutosSecosjCheckBox;
    private javax.swing.JLabel GRASASjLabel;
    private javax.swing.JCheckBox GalletaIntegraljCheckBox;
    private javax.swing.JCheckBox GarbanzosjCheckBox;
    private javax.swing.JCheckBox GuisantesjCheckBox;
    private javax.swing.JCheckBox HabaFrescajCheckBox;
    private javax.swing.JCheckBox HarinaTrigojCheckBox;
    private javax.swing.JCheckBox HuevojCheckBox;
    private javax.swing.JCheckBox HummusjCheckBox;
    private javax.swing.JCheckBox LecheEnterajCheckBox;
    private javax.swing.JCheckBox LechugajCheckBox;
    private javax.swing.JCheckBox LentejasjCheckBox;
    private javax.swing.JButton ListaDeComprasjButton;
    private javax.swing.JLabel LogojLabel;
    private javax.swing.JCheckBox ManzanajCheckBox;
    private javax.swing.JButton MetajButton;
    private javax.swing.JCheckBox NopalesjCheckBox;
    private javax.swing.JLabel PROTEINASjLabel;
    private javax.swing.JCheckBox PanAvenajCheckBox;
    private javax.swing.JCheckBox PanIntegraljCheckBox;
    private javax.swing.JCheckBox PapasjCheckBox;
    private javax.swing.JCheckBox PapayajCheckBox;
    private javax.swing.JCheckBox PastajCheckBox;
    private javax.swing.JCheckBox PavojCheckBox;
    private javax.swing.JCheckBox PechugaPollojCheckBox;
    private javax.swing.JCheckBox PepinojCheckBox;
    private javax.swing.JButton PerfiljButton;
    private javax.swing.JCheckBox PescadojCheckBox;
    private javax.swing.JCheckBox PlátanoMadurojCheckBox;
    private javax.swing.JCheckBox QuesoPanelajCheckBox;
    private javax.swing.JCheckBox RemolachajCheckBox;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JCheckBox SalmónjCheckBox;
    private javax.swing.JCheckBox SardinajCheckBox;
    private javax.swing.JCheckBox SemillaChíajCheckBox;
    private javax.swing.JCheckBox SemillasjCheckBox;
    private javax.swing.JButton SiguientejButton;
    private javax.swing.JCheckBox TahinijCheckBox;
    private javax.swing.JCheckBox TofujCheckBox;
    private javax.swing.JCheckBox TortillaTrigojCheckBox;
    private javax.swing.JLabel VERDURASjLabel;
    private javax.swing.JCheckBox YucaCocidajCheckBox;
    private javax.swing.JCheckBox ZanahoriajCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
