/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foodtrack;

/**
 *
 * @author hilar
 */
public class ListaCompras extends javax.swing.JFrame {

    /**
     * Creates new form ListaCompras
     */
    public ListaCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LogojLabel = new javax.swing.JLabel();
        AñadirComidajButton = new javax.swing.JButton();
        MetajButton = new javax.swing.JButton();
        ListaDeComprasjButton = new javax.swing.JButton();
        EstadisticasjButton = new javax.swing.JButton();
        PerfiljButton = new javax.swing.JButton();
        ConfiguracionjButton = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();
        PROTEINASjLabel = new javax.swing.JLabel();
        CARBOHIDRATOSjLabel = new javax.swing.JLabel();
        VERDURASjLabel = new javax.swing.JLabel();
        GRASASjLabel = new javax.swing.JLabel();
        HuevojRadioButton = new javax.swing.JRadioButton();
        AtúnLatajRadioButton = new javax.swing.JRadioButton();
        SardinajRadioButton = new javax.swing.JRadioButton();
        LentejasjRadioButton = new javax.swing.JRadioButton();
        EspinacasjRadioButton = new javax.swing.JRadioButton();
        GuisantesjRadioButton = new javax.swing.JRadioButton();
        GarbanzosjRadioButton = new javax.swing.JRadioButton();
        PescadojRadioButton = new javax.swing.JRadioButton();
        PechugaPollojRadioButton = new javax.swing.JRadioButton();
        OtroProtejLabel = new javax.swing.JLabel();
        AgregarProteinasTextField = new javax.swing.JTextField();
        SiguientejButton = new javax.swing.JButton();
        PanIntegraljRadioButton = new javax.swing.JRadioButton();
        ArrozCocidojRadioButton = new javax.swing.JRadioButton();
        AvenajRadioButton = new javax.swing.JRadioButton();
        PastajRadioButton = new javax.swing.JRadioButton();
        HarinaTrigojRadioButton = new javax.swing.JRadioButton();
        ManzanajRadioButton = new javax.swing.JRadioButton();
        PapayajRadioButton = new javax.swing.JRadioButton();
        PlatanoMadurojRadioButton = new javax.swing.JRadioButton();
        YucaCocidajRadioButton = new javax.swing.JRadioButton();
        OtroCarbojLabel = new javax.swing.JLabel();
        AgregarCarbohidratosjTextField = new javax.swing.JTextField();
        LechugajRadioButton = new javax.swing.JRadioButton();
        FrutosSecosjRadioButton = new javax.swing.JRadioButton();
        BrocolijRadioButton = new javax.swing.JRadioButton();
        SemillasjRadioButton = new javax.swing.JRadioButton();
        ColiflorjRadioButton = new javax.swing.JRadioButton();
        AceitunasjRadioButton = new javax.swing.JRadioButton();
        ApiojRadioButton = new javax.swing.JRadioButton();
        EdamamejRadioButton = new javax.swing.JRadioButton();
        PepinojRadioButton = new javax.swing.JRadioButton();
        TahinijRadioButton = new javax.swing.JRadioButton();
        ZanahoriajRadioButton = new javax.swing.JRadioButton();
        AceiteCocojRadioButton = new javax.swing.JRadioButton();
        RemolachajRadioButton = new javax.swing.JRadioButton();
        HummusjRadioButton = new javax.swing.JRadioButton();
        HabaFrescajRadioButton = new javax.swing.JRadioButton();
        TofujRadioButton = new javax.swing.JRadioButton();
        PapasjRadioButton = new javax.swing.JRadioButton();
        AceiteOlivajRadioButton = new javax.swing.JRadioButton();
        OtroVerdurasjLabel = new javax.swing.JLabel();
        OtroGrasasjLabel = new javax.swing.JLabel();
        AgregarVerdurasjTextField = new javax.swing.JTextField();
        AgregarGrasasjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 175));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        LogojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/foodtrack/Resources/logo_blanco.png"))); // NOI18N

        AñadirComidajButton.setBackground(new java.awt.Color(255, 255, 204));
        AñadirComidajButton.setText("Añadir comida");
        AñadirComidajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirComidajButtonActionPerformed(evt);
            }
        });

        MetajButton.setBackground(new java.awt.Color(255, 255, 204));
        MetajButton.setText("Meta");

        ListaDeComprasjButton.setBackground(new java.awt.Color(255, 255, 204));
        ListaDeComprasjButton.setText("Lista de compras");

        EstadisticasjButton.setBackground(new java.awt.Color(255, 255, 204));
        EstadisticasjButton.setText("Estadísticas");

        PerfiljButton.setBackground(new java.awt.Color(255, 255, 204));
        PerfiljButton.setText("Perfil");

        ConfiguracionjButton.setBackground(new java.awt.Color(255, 255, 204));
        ConfiguracionjButton.setText("Configuración");

        SalirjButton.setBackground(new java.awt.Color(255, 255, 204));
        SalirjButton.setText("Salir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AñadirComidajButton)
                            .addComponent(MetajButton)
                            .addComponent(ListaDeComprasjButton)
                            .addComponent(EstadisticasjButton)
                            .addComponent(PerfiljButton)
                            .addComponent(ConfiguracionjButton))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogojLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalirjButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LogojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AñadirComidajButton)
                .addGap(18, 18, 18)
                .addComponent(MetajButton)
                .addGap(18, 18, 18)
                .addComponent(ListaDeComprasjButton)
                .addGap(18, 18, 18)
                .addComponent(EstadisticasjButton)
                .addGap(18, 18, 18)
                .addComponent(PerfiljButton)
                .addGap(18, 18, 18)
                .addComponent(ConfiguracionjButton)
                .addGap(18, 18, 18)
                .addComponent(SalirjButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        PROTEINASjLabel.setForeground(new java.awt.Color(255, 51, 0));
        PROTEINASjLabel.setText("PROTEÍNAS");

        CARBOHIDRATOSjLabel.setForeground(new java.awt.Color(255, 51, 0));
        CARBOHIDRATOSjLabel.setText("CARBOHIDRATOS");

        VERDURASjLabel.setForeground(new java.awt.Color(255, 51, 0));
        VERDURASjLabel.setText("VERDURAS");

        GRASASjLabel.setForeground(new java.awt.Color(255, 51, 0));
        GRASASjLabel.setText("GRASAS SALUDABLES");

        HuevojRadioButton.setText("HUEVO");
        HuevojRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HuevojRadioButtonActionPerformed(evt);
            }
        });

        AtúnLatajRadioButton.setText("ATÚN EN LATA");

        SardinajRadioButton.setText("SARDINA");

        LentejasjRadioButton.setText("LENTEJAS");

        EspinacasjRadioButton.setText("ESPINACAS");

        GuisantesjRadioButton.setText("GUISANTES");

        GarbanzosjRadioButton.setText("GARBANZOS");

        PescadojRadioButton.setText("PESCADO");

        PechugaPollojRadioButton.setText("PECHUGA DE POLLO");

        OtroProtejLabel.setText("OTRO:");

        SiguientejButton.setBackground(new java.awt.Color(255, 102, 0));
        SiguientejButton.setText("SIGUIENTE>");

        PanIntegraljRadioButton.setText("PAN INTEGRAL");

        ArrozCocidojRadioButton.setText("ARROZ COCIDO");

        AvenajRadioButton.setText("AVENA");

        PastajRadioButton.setText("PASTA");
        PastajRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastajRadioButtonActionPerformed(evt);
            }
        });

        HarinaTrigojRadioButton.setText("HARINA DE TRIGO");

        ManzanajRadioButton.setText("MANZANA");

        PapayajRadioButton.setText("PAPAYA");

        PlatanoMadurojRadioButton.setText("PLÁTANO MADURO");

        YucaCocidajRadioButton.setText("YUCA COCIDA");

        OtroCarbojLabel.setText("OTRO:");

        LechugajRadioButton.setText("LECHUGA");

        FrutosSecosjRadioButton.setText("FRUTOS SECOS");

        BrocolijRadioButton.setText("BRÓCOLI");

        SemillasjRadioButton.setText("SEMILLAS");

        ColiflorjRadioButton.setText("COLIFLOR");

        AceitunasjRadioButton.setText("ACEITUNAS");

        ApiojRadioButton.setText("APIO");

        EdamamejRadioButton.setText("EDAMAME");

        PepinojRadioButton.setText("PEPINO");

        TahinijRadioButton.setText("TAHINI");

        ZanahoriajRadioButton.setText("ZANAHORIA");

        AceiteCocojRadioButton.setText("ACEITE DE COCO");

        RemolachajRadioButton.setText("REMOLACHA");

        HummusjRadioButton.setText("HUMMUS");

        HabaFrescajRadioButton.setText("HABA FRESCA");

        TofujRadioButton.setText("TOFU");

        PapasjRadioButton.setText("PAPAS");

        AceiteOlivajRadioButton.setText("ACEITE DE OLIVA");

        OtroVerdurasjLabel.setText("OTRO:");

        OtroGrasasjLabel.setText("OTRO:");

        AgregarVerdurasjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVerdurasjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HuevojRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SardinajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LentejasjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EspinacasjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuisantesjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GarbanzosjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PescadojRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(OtroProtejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarProteinasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PROTEINASjLabel)
                            .addComponent(AtúnLatajRadioButton)
                            .addComponent(PechugaPollojRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PanIntegraljRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AvenajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PastajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ManzanajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PapayajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(YucaCocidajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(OtroCarbojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AgregarCarbohidratosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CARBOHIDRATOSjLabel)
                                .addComponent(ArrozCocidojRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(HarinaTrigojRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlatanoMadurojRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LechugajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrocolijRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColiflorjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApiojRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PepinojRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZanahoriajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemolachajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HabaFrescajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PapasjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(OtroVerdurasjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarVerdurasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(VERDURASjLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OtroGrasasjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarGrasasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FrutosSecosjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SemillasjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AceitunasjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EdamamejRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TahinijRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HummusjRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TofujRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GRASASjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AceiteCocojRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AceiteOlivajRadioButton))
                                .addContainerGap(24, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SiguientejButton)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PROTEINASjLabel)
                    .addComponent(CARBOHIDRATOSjLabel)
                    .addComponent(VERDURASjLabel)
                    .addComponent(GRASASjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HuevojRadioButton)
                    .addComponent(PanIntegraljRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LechugajRadioButton)
                    .addComponent(FrutosSecosjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtúnLatajRadioButton)
                    .addComponent(ArrozCocidojRadioButton)
                    .addComponent(BrocolijRadioButton)
                    .addComponent(SemillasjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SardinajRadioButton)
                    .addComponent(AvenajRadioButton)
                    .addComponent(ColiflorjRadioButton)
                    .addComponent(AceitunasjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LentejasjRadioButton)
                    .addComponent(PastajRadioButton)
                    .addComponent(ApiojRadioButton)
                    .addComponent(EdamamejRadioButton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EspinacasjRadioButton)
                            .addComponent(HarinaTrigojRadioButton)
                            .addComponent(PepinojRadioButton)
                            .addComponent(TahinijRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GuisantesjRadioButton)
                            .addComponent(ManzanajRadioButton)
                            .addComponent(ZanahoriajRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GarbanzosjRadioButton)
                            .addComponent(PapayajRadioButton)
                            .addComponent(RemolachajRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PescadojRadioButton)
                            .addComponent(PlatanoMadurojRadioButton)
                            .addComponent(HabaFrescajRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YucaCocidajRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PechugaPollojRadioButton)
                                .addComponent(PapasjRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OtroProtejLabel)
                            .addComponent(AgregarProteinasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OtroCarbojLabel)
                            .addComponent(AgregarCarbohidratosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OtroVerdurasjLabel)
                            .addComponent(AgregarVerdurasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(AceiteCocojRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HummusjRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TofujRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AceiteOlivajRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OtroGrasasjLabel)
                            .addComponent(AgregarGrasasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SiguientejButton)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarVerdurasjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVerdurasjTextFieldActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarVerdurasjTextFieldActionPerformed

    private void PastajRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastajRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PastajRadioButtonActionPerformed

    private void AñadirComidajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirComidajButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirComidajButtonActionPerformed

    private void HuevojRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HuevojRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HuevojRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AceiteCocojRadioButton;
    private javax.swing.JRadioButton AceiteOlivajRadioButton;
    private javax.swing.JRadioButton AceitunasjRadioButton;
    private javax.swing.JTextField AgregarCarbohidratosjTextField;
    private javax.swing.JTextField AgregarGrasasjTextField;
    private javax.swing.JTextField AgregarProteinasTextField;
    private javax.swing.JTextField AgregarVerdurasjTextField;
    private javax.swing.JRadioButton ApiojRadioButton;
    private javax.swing.JRadioButton ArrozCocidojRadioButton;
    private javax.swing.JRadioButton AtúnLatajRadioButton;
    private javax.swing.JRadioButton AvenajRadioButton;
    private javax.swing.JButton AñadirComidajButton;
    private javax.swing.JRadioButton BrocolijRadioButton;
    private javax.swing.JLabel CARBOHIDRATOSjLabel;
    private javax.swing.JRadioButton ColiflorjRadioButton;
    private javax.swing.JButton ConfiguracionjButton;
    private javax.swing.JRadioButton EdamamejRadioButton;
    private javax.swing.JRadioButton EspinacasjRadioButton;
    private javax.swing.JButton EstadisticasjButton;
    private javax.swing.JRadioButton FrutosSecosjRadioButton;
    private javax.swing.JLabel GRASASjLabel;
    private javax.swing.JRadioButton GarbanzosjRadioButton;
    private javax.swing.JRadioButton GuisantesjRadioButton;
    private javax.swing.JRadioButton HabaFrescajRadioButton;
    private javax.swing.JRadioButton HarinaTrigojRadioButton;
    private javax.swing.JRadioButton HuevojRadioButton;
    private javax.swing.JRadioButton HummusjRadioButton;
    private javax.swing.JRadioButton LechugajRadioButton;
    private javax.swing.JRadioButton LentejasjRadioButton;
    private javax.swing.JButton ListaDeComprasjButton;
    private javax.swing.JLabel LogojLabel;
    private javax.swing.JRadioButton ManzanajRadioButton;
    private javax.swing.JButton MetajButton;
    private javax.swing.JLabel OtroCarbojLabel;
    private javax.swing.JLabel OtroGrasasjLabel;
    private javax.swing.JLabel OtroProtejLabel;
    private javax.swing.JLabel OtroVerdurasjLabel;
    private javax.swing.JLabel PROTEINASjLabel;
    private javax.swing.JRadioButton PanIntegraljRadioButton;
    private javax.swing.JRadioButton PapasjRadioButton;
    private javax.swing.JRadioButton PapayajRadioButton;
    private javax.swing.JRadioButton PastajRadioButton;
    private javax.swing.JRadioButton PechugaPollojRadioButton;
    private javax.swing.JRadioButton PepinojRadioButton;
    private javax.swing.JButton PerfiljButton;
    private javax.swing.JRadioButton PescadojRadioButton;
    private javax.swing.JRadioButton PlatanoMadurojRadioButton;
    private javax.swing.JRadioButton RemolachajRadioButton;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JRadioButton SardinajRadioButton;
    private javax.swing.JRadioButton SemillasjRadioButton;
    private javax.swing.JButton SiguientejButton;
    private javax.swing.JRadioButton TahinijRadioButton;
    private javax.swing.JRadioButton TofujRadioButton;
    private javax.swing.JLabel VERDURASjLabel;
    private javax.swing.JRadioButton YucaCocidajRadioButton;
    private javax.swing.JRadioButton ZanahoriajRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
