/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foodtrack;

import javax.swing.JOptionPane;

/**
 *
 * @author monyv
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoS = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        imgSiluetas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RadioHombre = new javax.swing.JRadioButton();
        RadioMujer = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        pesoInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        alturaInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usuarioInput = new javax.swing.JTextField();
        correoInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        titulo = new javax.swing.JLabel();
        apellidoInput = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        registrarse = new javax.swing.JButton();
        RegresarBtn = new javax.swing.JButton();
        edadInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 244, 192));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        imgSiluetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/foodtrack/Resources/siluetas.png"))); // NOI18N

        jLabel1.setText("Nombre:");

        nombreInput.setBackground(new java.awt.Color(253, 140, 13));

        jLabel2.setText("Edad:");

        jLabel3.setText("Sexo:");

        RadioHombre.setBackground(new java.awt.Color(253, 140, 13));
        grupoS.add(RadioHombre);
        RadioHombre.setText("Hombre");
        RadioHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioHombreActionPerformed(evt);
            }
        });

        RadioMujer.setBackground(new java.awt.Color(253, 140, 13));
        grupoS.add(RadioMujer);
        RadioMujer.setSelected(true);
        RadioMujer.setText("Mujer");

        jLabel4.setText("Peso (Kg):");

        pesoInput.setBackground(new java.awt.Color(253, 140, 13));

        jLabel5.setText("Altura (Mts):");

        alturaInput.setBackground(new java.awt.Color(253, 140, 13));

        jLabel6.setText("Usuario:");

        jLabel7.setText("Correo:");

        jLabel8.setText("Contraseña:");

        usuarioInput.setBackground(new java.awt.Color(253, 140, 13));

        correoInput.setBackground(new java.awt.Color(253, 140, 13));
        correoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoInputActionPerformed(evt);
            }
        });

        passwordInput.setBackground(new java.awt.Color(253, 140, 13));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setText("Registro");
        titulo.setToolTipText("");

        apellidoInput.setBackground(new java.awt.Color(253, 140, 13));

        apellidoLabel.setText("Apellido:");

        registrarse.setBackground(new java.awt.Color(253, 140, 13));
        registrarse.setText("Registrarse");
        registrarse.setToolTipText("Rexgistrarse");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        RegresarBtn.setBackground(new java.awt.Color(253, 140, 13));
        RegresarBtn.setText("Regresar");
        RegresarBtn.setToolTipText("Regresar");
        RegresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBtnActionPerformed(evt);
            }
        });

        edadInput.setBackground(new java.awt.Color(253, 140, 13));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RegresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(179, 179, 179))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgSiluetas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RadioMujer)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(edadInput)
                                                    .addComponent(nombreInput, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                        .addComponent(apellidoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellidoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(correoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(usuarioInput)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passwordInput))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioHombre))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(alturaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pesoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(67, 67, 67)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(RegresarBtn))
                .addGap(33, 33, 33)
                .addComponent(imgSiluetas)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(edadInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(RadioHombre)
                            .addComponent(RadioMujer))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pesoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(alturaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(usuarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoInputActionPerformed

    private void RadioHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioHombreActionPerformed

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed

       //*OBtener datos del formulario*//
       int idSexo=RadioHombre.isSelected()? 1:2;
       String nombre=nombreInput.getText().trim();
       String apellido=apellidoInput.getText().trim();
       int edad =Integer.parseInt(edadInput.getText().trim());
       double peso=Double.parseDouble(pesoInput.getText().trim());
       double altura=Double.parseDouble(alturaInput.getText().trim());
       String nom_usuario=usuarioInput.getText().trim();
       String correo= correoInput.getText().trim();
       String contrasena =new String(passwordInput.getPassword()).trim();
       double imc=peso/(altura*altura);
       //*Lllamar a la BD*//
       boolean registrado = PeticionesDB.registrarUsuario(idSexo, nombre, apellido, edad, peso, altura, nom_usuario, correo, contrasena, imc);
       //*verificar si se registro correctamente*//
       if(registrado){
           JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
           Login login=new Login();
           login.setVisible(true);
           dispose();          
       } else{
           JOptionPane.showMessageDialog(this, "Error al registar el usuario","Error", JOptionPane.ERROR_MESSAGE);
       }
        // TODO add your handling code here:
    if (nombreInput.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de nombre está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }   
    if (apellidoInput.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de apellido está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (edadInput.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de edad está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
   
    if (RadioHombre.isSelected() && RadioMujer.isSelected() ){
    JOptionPane.showMessageDialog(this, "️ El campo sexo  está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (pesoInput.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de peso está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (alturaInput.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de altura está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (usuarioInput.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de usuario está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (correoInput.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de correo está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
     if (new String(passwordInput.getPassword()).trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "️ El campo de contraseña está vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
        Login miLogin = new Login();
        miLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_registrarseActionPerformed

    private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBtnActionPerformed
        // TODO add your handling code here:
       Login miLogin = new Login();
        miLogin.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_RegresarBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioHombre;
    private javax.swing.JRadioButton RadioMujer;
    private javax.swing.JButton RegresarBtn;
    private javax.swing.JTextField alturaInput;
    private javax.swing.JTextField apellidoInput;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JTextField correoInput;
    private javax.swing.JTextField edadInput;
    private javax.swing.ButtonGroup grupoS;
    private javax.swing.JLabel imgSiluetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreInput;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField pesoInput;
    private javax.swing.JButton registrarse;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField usuarioInput;
    // End of variables declaration//GEN-END:variables
}
