/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.foodtrack;
import java.util.List;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.io.FileWriter;
import java.util.ArrayList;
import java.io.BufferedWriter;
/**
 *
 * @author hilar
 */
public class SeleccionListaCompras extends javax.swing.JFrame {
    ArrayList<String> alimentosSeleccionados = new ArrayList<>();

    /**
     * Creates new form SeleccionListaCompras
     */
    public SeleccionListaCompras() {
        initComponents();
    }
    private void guardarListaEnArchivo(){
        try{
            BufferedWriter escritor = new BufferedWriter(new FileWriter("Seleccion_Lista_compras.txt"));
            for(String alimento : alimentosSeleccionados){
                escritor.write(alimento + "\n");
                escritor.newLine();
                
            }
            escritor.close();
            JOptionPane.showMessageDialog(null,"Lista guardada exitosamente");
            
        }catch (IOException ex){
            JOptionPane.showMessageDialog(null, "Error al guardar la lista :" + ex.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AñadirComidaButton = new javax.swing.JButton();
        ListaDeComprasButton = new javax.swing.JButton();
        EstadísticasButton = new javax.swing.JButton();
        PerfilButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        seleccionadosTextArea = new javax.swing.JTextArea();
        GuardarListaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 222, 175));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/foodtrack/Resources/logo_blanco.png"))); // NOI18N

        AñadirComidaButton.setBackground(new java.awt.Color(255, 255, 204));
        AñadirComidaButton.setText("Añadir comida");
        AñadirComidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirComidaButtonActionPerformed(evt);
            }
        });

        ListaDeComprasButton.setBackground(new java.awt.Color(255, 255, 204));
        ListaDeComprasButton.setText("Lista de compras");
        ListaDeComprasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDeComprasButtonActionPerformed(evt);
            }
        });

        EstadísticasButton.setBackground(new java.awt.Color(255, 255, 204));
        EstadísticasButton.setText("Estadísticas");
        EstadísticasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadísticasButtonActionPerformed(evt);
            }
        });

        PerfilButton.setBackground(new java.awt.Color(255, 255, 204));
        PerfilButton.setText("Perfil");
        PerfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilButtonActionPerformed(evt);
            }
        });

        SalirButton.setBackground(new java.awt.Color(255, 255, 204));
        SalirButton.setText("Salir");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SalirButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(AñadirComidaButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(ListaDeComprasButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(EstadísticasButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(PerfilButton))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AñadirComidaButton)
                .addGap(33, 33, 33)
                .addComponent(ListaDeComprasButton)
                .addGap(33, 33, 33)
                .addComponent(EstadísticasButton)
                .addGap(32, 32, 32)
                .addComponent(PerfilButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalirButton)
                .addGap(36, 36, 36))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("ALIMENTOS SELECCIONADOS");

        seleccionadosTextArea.setBackground(new java.awt.Color(255, 252, 235));
        seleccionadosTextArea.setColumns(20);
        seleccionadosTextArea.setRows(5);
        jScrollPane1.setViewportView(seleccionadosTextArea);

        GuardarListaButton.setBackground(new java.awt.Color(255, 102, 0));
        GuardarListaButton.setText("Guardar lista");
        GuardarListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarListaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GuardarListaButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GuardarListaButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirComidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirComidaButtonActionPerformed

       AddComida miaddcomida= new AddComida();
        miaddcomida.setVisible(true);
       this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirComidaButtonActionPerformed

    private void ListaDeComprasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDeComprasButtonActionPerformed

        ListaCompras listaPantalla = new ListaCompras();
        listaPantalla.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaDeComprasButtonActionPerformed

    private void EstadísticasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadísticasButtonActionPerformed

       Estadisticas estadisticasPantalla = new Estadisticas();
       estadisticasPantalla.setVisible(true);
       this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadísticasButtonActionPerformed

    private void PerfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilButtonActionPerformed

      Perfil perfilPantalla = new Perfil();
      perfilPantalla.setVisible(true);
      this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void GuardarListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarListaButtonActionPerformed
 
        guardarListaEnArchivo();
// TODO add your handling code here:

    }//GEN-LAST:event_GuardarListaButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    public SeleccionListaCompras(List<String> alimentosSeleccionados){
        initComponents();
        //Mostrar los alimentos en el JTextArea
        StringBuilder texto = new StringBuilder();
        for (String alimento : alimentosSeleccionados){
            texto.append("-").append(alimento).append("/n");
        }
        seleccionadosTextArea.setText(texto.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirComidaButton;
    private javax.swing.JButton EstadísticasButton;
    private javax.swing.JButton GuardarListaButton;
    private javax.swing.JButton ListaDeComprasButton;
    private javax.swing.JButton PerfilButton;
    private javax.swing.JButton SalirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea seleccionadosTextArea;
    // End of variables declaration//GEN-END:variables
}
